# Generated by Django 3.2 on 2022-04-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_approve_project', 'Pode aprovar projeto'),), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
