# Generated by Django 3.2 on 2022-04-17 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucional', '0001_initial'),
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=150, verbose_name='Telefone(s)')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('detalhamento', models.TextField(verbose_name='Detalhamento')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Longitude')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação')),
                ('prazo_execucao', models.IntegerField(verbose_name='Prazo de execução (meses)')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projeto_created_by', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto_responsavel', to='planejamento.responsavel')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto_secretaria', to='institucional.secretaria')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projeto_status', to='contrib.projetostatus')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto_orcamento', to='contrib.projetotipo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto_orcamento', to='contrib.unidadetipo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projeto_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ano', models.IntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')], verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='financeiro_created_by', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_projeto', to='planejamento.projeto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='financeiro_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento Financeiro',
                'verbose_name_plural': 'Planejamento Financeiro',
            },
        ),
    ]
