# Generated by Django 3.2 on 2022-04-17 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='financeiro_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='financeiro_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projeto_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto_responsavel', to='planejamento.responsavel', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projeto_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterUniqueTogether(
            name='financeiro',
            unique_together={('projeto', 'ano')},
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modificado em')),
                ('data', models.DateTimeField(verbose_name='Data/Hora')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acompanhamento_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acompanhamento_projeto', to='planejamento.projeto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acompanhamento_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
            },
        ),
    ]
