# Generated by Django 3.2 on 2022-04-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0002_auto_20220417_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='status',
        ),
    ]
