# Generated by Django 3.2 on 2022-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0003_auto_20220417_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_ultimo_acompanhamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do último acompanhamento'),
        ),
    ]
