# Generated by Django 3.2 on 2022-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0003_remove_projeto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cadastrado'), (1, 'Proposta'), (2, 'Aprovado'), (3, 'Pendente'), (4, 'Negado')], default=0, verbose_name='Status'),
        ),
    ]
