# Generated by Django 3.2 on 2022-05-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0005_alter_projeto_data_ultimo_acompanhamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'permissions': (('can_approve', 'Pode aprovar projeto'),), 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
