# Generated by Django 3.2 on 2022-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modificado em')),
                ('codigo', models.CharField(max_length=8, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de projeto',
                'verbose_name_plural': 'Tipos de projeto',
            },
        ),
        migrations.CreateModel(
            name='UnidadeTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modificado em')),
                ('codigo', models.CharField(max_length=8, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de unidade',
                'verbose_name_plural': 'Tipos de unidade',
            },
        ),
    ]
