# Generated by Django 3.2 on 2022-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modificado em')),
                ('codigo', models.CharField(max_length=8, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_criacao', models.DateTimeField(verbose_name='Data de criação')),
                ('data_extincao', models.DateTimeField(blank=True, null=True, verbose_name='Data de extinção')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modificado em')),
                ('codigo', models.CharField(max_length=8, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_criacao', models.DateTimeField(verbose_name='Data de criação')),
                ('data_extincao', models.DateTimeField(blank=True, null=True, verbose_name='Data de extinção')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
    ]
