# Generated by Django 3.2 on 2022-04-17 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretaria',
            options={'verbose_name': 'Secretaria', 'verbose_name_plural': 'Secretarias'},
        ),
        migrations.AlterField(
            model_name='orgao',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgao_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgao_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretaria_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretaria_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
