# Generated by Django 3.2 on 2022-04-17 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucional', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='data_criacao',
            field=models.DateField(verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_extincao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de extinção'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='data_criacao',
            field=models.DateField(verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='data_extincao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de extinção'),
        ),
        migrations.CreateModel(
            name='CorpoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modificado em')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corpotecnico_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corpotecnico_orgao', to='institucional.orgao', verbose_name='Órgão')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corpotecnico_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corpotecnico_user', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Corpo técnico',
                'verbose_name_plural': 'Corpo técnico',
            },
        ),
    ]
